# Copyright (c) ZNbase, Inc.
#
# To analyze (without uploading to Fossa) -- for local debugging:
# fossa analyze --debug --output
#
# To analyze and upload dependencies:
# fossa analyze --debug

version: 2
cli:
  server: https://app.fossa.com
  fetcher: custom
  project: git@github.com:ZNbase/ZNbase-db.git
analyze:
  modules:
    - name: ZNbase RPC Client
      type: mvn
      target: pom.xml
      path: java
      options:
        cmd: |
          set -euo pipefail -x
          cd java
          mvn --batch-mode dependency:tree
    - name: ZNbase Platform
      type: mvn
      target: pom.xml
      path: managed
      options:
        cmd: |
          set -euo pipefail -x
          cd managed
          mvn --batch-mode dependency:tree -f "$(
            USE_MAVEN_LOCAL=true sbt -Dsbt.log.noformat=true make-pom | perl -n -e '/^\[info\] Wrote (.*[.]pom)$/ && print $1'
          )"
    - name: ui
      type: npm
      target: managed/ui
      path: managed/ui
    - name: opscli
      type: pip
      target: managed/devops
      path: managed/devops
      options:
        requirements: managed/devops/python_requirements_frozen.txt
    - name: PostgreSQL
      type: raw
      target: src/postgres
    - name: ZNbaseDB
      type: raw
      target: src/yb
